var buttonColours = ["red", "blue", "green", "yellow"]; 

var gamePattern = []; // The pattern generated by the game that the user has to follow

var userClickedPattern = []; // The pattern of colors that the user has clicked in the current level

var started = false; 

var level = 0;

function startGame() {  
    if(!started){ 
        $("#level-title").text("Level " + level);  
        nextSequence(); 
        started = true; 
    }
}

// Desktop start: keypress listener (for keybords)
$(document).keypress(function(){ 
    startGame();
});

// Mobile start: Click/Touch listener on the Title/Start button
$("#level-title").on("click touchstart", function(event){
    // Prevent default touch behaviour
    event.preventDefault();
    startGame();
});

$(".btn").click(function(){ 
        var userChosenColour = $(this).attr("id"); // Get the id of the button that was clicked, which corresponds to the color
        userClickedPattern.push(userChosenColour); // Add the color to the user's pattern

        playSound(userChosenColour);
        animatePress(userChosenColour);

        checkAnswer(userClickedPattern.length-1) // Check the user's answer by passing the index of the last color they clicked
});

function checkAnswer(currentLevel){ // Check if the most recent user click matches the game pattern at the same index 
    if(gamePattern[currentLevel] === userClickedPattern[currentLevel]){ 

        console.log("Success");

        if(userClickedPattern.length === gamePattern.length){ 
            setTimeout(function(){ // If the user has completed the current pattern, call nextSequence() after a 1 second delay to generate the next pattern
                nextSequence(); 
            }, 1000);
        }
    }
    else{
        console.log("Wrong");

        playSound("wrong");

        $("body").addClass("game-over");
        setTimeout(function(){
            $("body").removeClass("game-over"); // Remove the "game-over" class after a 200ms delay to create a flash effect when the user gets the pattern wrong
        }, 200);

        $("#level-title").text("Game Over, Tap to Restart");

        startOver();
    }
}

function nextSequence(){ // Reset the user's pattern for the new level

    userClickedPattern = []; 
    
    level++;
    $("#level-title").text("Level " + level);

    var randomNumber = Math.floor(Math.random() * 4); // Generate a random number between 0 and 3 to select a random color from the buttonColours array
    var randomChosenColour = buttonColours[randomNumber];
    gamePattern.push(randomChosenColour);

    $("#" + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100); 
    playSound(randomChosenColour); 
    
}

function playSound(name){ // Create a new Audio object with the corresponding sound file and play it
    var audio = new Audio("sounds/" + name + ".mp3");
    audio.play();
}

function animatePress(currentColor){ // Animate the button press effect
    $("#" + currentColor).addClass("pressed");
    setTimeout(function(){
        $("#" + currentColor).removeClass("pressed");
    }, 100);
}

function startOver(){ // Reset the game variables to their initial state to allow the user to restart the game
    level = 0;
    gamePattern = [];
    started = false;
}